blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://github.com/lichess-org/lila/issues
    about: Issues about the lichess website are tracked in a seperate repository.
  - name: Old Mobile app
    url: https://github.com/lichess-org/lichobile/issues
    about: Issues for the old mobile app are tracked in a separate repository. Please check for duplicates first.
  - name: Support
    url: https://discord.gg/lichess
    about: GitHub issues are meant for tracking enhancements and bugs, not general support. Instead, search the Wiki, Lichess Forum, StackOverflow, or join our Discord.
