name: DCM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: dcm-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dcm
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fatal_warnings: true
          fatal_performance: true
